export enum EventType {
  GLTFloaded = "GLTFloaded",
  AnimationsReady = "AnimationsReady",
  Render = "Render",
  RemoveRender = "RemoveRender",
  AnimationMixerLoaded = "AnimationMixer",
  ChangGeometry = "ChangGeometry",
  ChangTexture = "ChangTexture",
  ChangMaterial = "ChangMaterial",
  RemoveMesh = "RemoveMesh",
  ChangMesh = "ChangMesh",
  AddObject3d = "AddObject3d",
  RenderSizeChang = "RenderSizeChang",
}
/** SDEvent is sandi-ui Event*/
export enum SDEvent {
  onClick = "click",
  onPointerOver = "pointerover",
  onPointerOut = "pointerout",
  onPointerMove = "pointermove",
  onPointerDown = "pointerdown",
  onPointerUp = "pointerup",
  onWheel = "wheel",
  onDblClick = "dblclick",
  onPointerMissed = "pointermissed",
  onKeyMissed = "keymissed",
  None = "none",
  onKeyDown = "keydown",
  onKeyup = "keyup",
  onKeypress = "keypress",
  onContextmenu = "contextmenu",
}
